import {
  CreditCardIcon,
  HomeIcon,
  TruckIcon,
  ShoppingCartIcon,
  PhoneIcon,
  WifiIcon,
  HeartIcon,
  WrenchIcon,
  BookOpenIcon,
  FilmIcon,
  GiftIcon,
  PaperAirplaneIcon,
  SparklesIcon,
  BoltIcon,
  CloudIcon,
  FireIcon,
  BanknotesIcon,
  BuildingLibraryIcon,
  AcademicCapIcon,
  BriefcaseIcon,
  CakeIcon,
  ChatBubbleLeftRightIcon,
  ComputerDesktopIcon,
  DevicePhoneMobileIcon,
  GlobeAltIcon,
  KeyIcon,
  LightBulbIcon,
  MapPinIcon,
  MusicalNoteIcon,
  PuzzlePieceIcon,
  QrCodeIcon,
  RadioIcon,
  RocketLaunchIcon,
  ScaleIcon,
  ScissorsIcon,
  ShieldCheckIcon,
  TicketIcon,
  TrophyIcon,
  UserIcon,
  VideoCameraIcon,
  WalletIcon,
} from "@heroicons/react/24/outline";
import {
  BusIcon,
  CoinsIcon,
  ParkingIcon,
  GasStationIcon,
  TaxiIcon,
} from "../components/CustomIcons";

export const builtinIconComponents = {
  "credit-card": CreditCardIcon,
  home: HomeIcon,
  truck: TruckIcon,
  "shopping-cart": ShoppingCartIcon,
  phone: PhoneIcon,
  wifi: WifiIcon,
  heart: HeartIcon,
  wrench: WrenchIcon,
  "book-open": BookOpenIcon,
  film: FilmIcon,
  gift: GiftIcon,
  plane: PaperAirplaneIcon,
  sparkles: SparklesIcon,
  bolt: BoltIcon,
  cloud: CloudIcon,
  fire: FireIcon,
  banknotes: BanknotesIcon,
  bank: BuildingLibraryIcon,
  education: AcademicCapIcon,
  briefcase: BriefcaseIcon,
  cake: CakeIcon,
  chat: ChatBubbleLeftRightIcon,
  computer: ComputerDesktopIcon,
  mobile: DevicePhoneMobileIcon,
  internet: GlobeAltIcon,
  key: KeyIcon,
  lightbulb: LightBulbIcon,
  location: MapPinIcon,
  music: MusicalNoteIcon,
  puzzle: PuzzlePieceIcon,
  qrcode: QrCodeIcon,
  radio: RadioIcon,
  rocket: RocketLaunchIcon,
  scale: ScaleIcon,
  scissors: ScissorsIcon,
  shield: ShieldCheckIcon,
  ticket: TicketIcon,
  trophy: TrophyIcon,
  user: UserIcon,
  video: VideoCameraIcon,
  wallet: WalletIcon,
  bus: BusIcon,
  coins: CoinsIcon,
  parking: ParkingIcon,
  gas: GasStationIcon,
  taxi: TaxiIcon,
} as const;

export const builtinIcons = Object.keys(builtinIconComponents) as BuiltinIcon[];

export type BuiltinIcon = keyof typeof builtinIconComponents;
